/**
 * Pure derivation for the reasoning screen (ticket #79, feature-list item
 * 21). No I/O — takes an already-resolved `ReasoningRecommendationData | null`
 * (see api.ts) and returns a fully-resolved `ReasoningView` the screen
 * renders with no further logic, same split as `src/lib/verdict/derive.ts`
 * (pure + tested) and `Pitch.tsx`'s pitchLayout.ts split.
 *
 * design-reference.md's Linear reference names THIS screen as the one place
 * in the app where information density is correct — every stored reason
 * line, the full component breakdown, coverage and the model version all
 * render here, none of it hidden behind a summary. product-brief.md §8
 * still governs: decimals are permitted ONLY here (never on the verdict
 * card or anywhere else), and every projected-points value must carry
 * context — a bare number next to nothing is exactly what this rule bans.
 */
import { formatSyncTimestamp } from '../format.ts'
import type {
  AlternativePlanData,
  ConfidenceBand,
  CoverageEntry,
  PlayerProjectionData,
  PlayerProjectionDriver,
  PlayerProjectionLearned,
  ReasoningRecommendationData,
  StartingXIPick,
} from './types.ts'

function nameFor(id: number, names: ReadonlyMap<number, string>): string {
  return names.get(id) ?? 'Unknown player'
}

// ============================================================================
// Component-label formatting — DELIBERATELY generic. `player_projections
// .components.points` is written by scripts/project-points.ts with whatever
// keys the model computes (appearancePoints, goalPoints, ... today; #78 adds
// nothing new here, a real bonus number just starts flowing through the same
// key). This function turns ANY camelCase `*Points` key into a sentence-case
// label — it does not enumerate the keys it expects, so an unrecognised key
// (a future model input) still renders with a readable label instead of
// being silently dropped. See derive.test.ts's "unknown component key" test.
// ============================================================================

const TRAILING_POINTS = /Points$/

export function formatComponentLabel(key: string): string {
  const trimmed = key.replace(TRAILING_POINTS, '')
  const spaced = trimmed.replace(/([a-z0-9])([A-Z])/g, '$1 $2').trim().toLowerCase()
  const label = spaced.length > 0 ? spaced : 'points'
  return label.charAt(0).toUpperCase() + label.slice(1)
}

export interface ReasoningComponentRow {
  key: string
  label: string
  value: number
}

/** Every entry in a player's `components.points` object, as display rows —
 *  iterates the object's OWN keys (ticket DoD), never a fixed list. Sorted
 *  by nothing but insertion order (`Object.entries`), matching the order
 *  scripts/project-points.ts writes them in — stable and not something this
 *  file re-decides. */
function pointsToRows(points: Readonly<Record<string, number>>): ReasoningComponentRow[] {
  return Object.entries(points).map(([key, value]) => ({
    key,
    label: formatComponentLabel(key),
    value,
  }))
}

// ============================================================================
// Learned-model drivers (ticket #266) — once `gbm-v1` decides a pick, the
// reasoning screen names it and gives the top three reasons in plain words,
// with the baseline-v1 breakdown kept underneath as the explainer. Feature
// names are GENERATED by model/fpl_model/features.py (`r{k}_{stat}`,
// `p90_{k}_{stat}`, ...), so this maps the pattern, never a fixed list of
// every name — the same principle formatComponentLabel above already
// follows for baseline-v1's component keys. An unrecognised name returns
// null and is dropped by the caller, never shown as a raw feature name.
// ============================================================================

/** `model/fpl_model/features.py`'s `_STAT_COLS` (plus the two derived
 *  minutes-based flags, `m60`/`app`) in plain words — shared by the `r{k}_`
 *  and `p90_{k}_` patterns below, since both roll the same underlying
 *  stats. Keys are exactly the Python column names; values are the ticket's
 *  own wording. */
const STAT_WORDS: Readonly<Record<string, string>> = {
  minutes: 'minutes',
  total_points: 'points',
  goals_scored: 'goals',
  assists: 'assists',
  expected_goals: 'expected goals',
  expected_assists: 'expected assists',
  bps: 'bonus points system',
  bonus: 'bonus',
  ict_index: 'ICT index',
  threat: 'threat',
  creativity: 'creativity',
  saves: 'saves',
  clean_sheets: 'clean sheets',
  goals_conceded: 'goals conceded',
  starts: 'starts',
  defensive_contribution: 'defensive contributions',
  expected_goals_conceded: 'expected goals conceded',
  m60: '60+ minute games',
  app: 'appearances',
}

/** Every feature name that is NOT a `r{k}_`/`p90_{k}_` rolling stat — a
 *  fixed set (context, market and odds features, per
 *  model/fpl_model/features.py's `_CONTEXT`/`_MARKET` plus the four odds
 *  names #133 adds), so a plain lookup is enough; no pattern needed.
 *  `pos_i` (position, encoded 0-3 by `_POSITION_CODE`) is in `_CONTEXT` but
 *  not named explicitly in this ticket's own list — described the same way
 *  as its siblings here rather than left to fall through to "unknown",
 *  since the ticket's DoD requires every FEATURES name to get a
 *  description. */
const NAMED_FEATURES: Readonly<Record<string, string>> = {
  own_pct_rank: 'popular with managers',
  transfers_rank: 'being transferred in',
  value: 'price',
  was_home: 'playing at home',
  nfix: 'number of fixtures',
  sd_minutes: 'minutes this season',
  sd_apps: 'appearances this season',
  rows_hist: 'games of history',
  pos_i: 'playing position',
  lambda_for: 'expected team goals this fixture',
  lambda_against: 'expected goals against',
  p_win: 'chance of winning',
  p_cs: 'clean-sheet chance',
}

const ROLLING_FEATURE = /^r(\d+)_(.+)$/
const P90_FEATURE = /^p90_(\d+)_(.+)$/
const TEAM_FEATURE = /^t_(gf|ga)_(\d+)$/
const OPPONENT_TEAM_FEATURE = /^ot_(gf|ga)_(\d+)$/

/** Turns one `gbm-v1` driver's generated feature name into plain words, or
 *  `null` when the name is not recognised — the caller drops those, never
 *  rendering a raw feature name (ticket DoD). Exported for
 *  `derive.test.ts`'s exhaustive `FEATURES` coverage. */
export function describeDriver(feature: string): string | null {
  const named = NAMED_FEATURES[feature]
  if (named) return named

  const rolling = feature.match(ROLLING_FEATURE)
  if (rolling) {
    const stat = STAT_WORDS[rolling[2]]
    if (stat) {
      const k = rolling[1]
      return k === '1' ? `${stat} last game` : `${stat} over the last ${k} games`
    }
  }

  const p90 = feature.match(P90_FEATURE)
  if (p90) {
    const stat = STAT_WORDS[p90[2]]
    if (stat) return `${stat} per 90 minutes, last ${p90[1]} games`
  }

  const team = feature.match(TEAM_FEATURE)
  if (team) {
    const [, stat, k] = team
    return `team goals ${stat === 'gf' ? 'scored' : 'conceded'}, last ${k}`
  }

  const opponentTeam = feature.match(OPPONENT_TEAM_FEATURE)
  if (opponentTeam) {
    const [, stat, k] = opponentTeam
    return `opponent goals ${stat === 'gf' ? 'scored' : 'conceded'}, last ${k}`
  }

  return null
}

/** "pushes up" for a non-negative contribution, "pulls down" for a negative
 *  one — the ticket's own wording, from the sign of `contribution` alone. */
export function driverDirection(contribution: number): 'pushes up' | 'pulls down' {
  return contribution >= 0 ? 'pushes up' : 'pulls down'
}

export interface ReasoningDriverView {
  feature: string
  description: string
  direction: 'pushes up' | 'pulls down'
}

/** The top three drivers by |contribution|, described in plain words —
 *  unrecognised names are dropped before ranking, never shown, so "top
 *  three" always means three DESCRIBED reasons rather than three raw slots
 *  that might include an unlabelled one. */
function topDrivers(drivers: readonly PlayerProjectionDriver[]): ReasoningDriverView[] {
  return drivers
    .map((driver) => {
      const description = describeDriver(driver.feature)
      return description === null
        ? null
        : { feature: driver.feature, description, contribution: driver.contribution }
    })
    .filter((entry): entry is { feature: string; description: string; contribution: number } => entry !== null)
    .sort((a, b) => Math.abs(b.contribution) - Math.abs(a.contribution))
    .slice(0, 3)
    .map(({ feature, description, contribution }) => ({
      feature,
      description,
      direction: driverDirection(contribution),
    }))
}

export interface ReasoningLearnedView {
  /** "Decided by gbm-v1 · 5.8" — the ticket's own line, pre-built here so
   *  the screen has no formatting logic of its own to get wrong. */
  headline: string
  /** Top three, described, non-empty whenever `learned.drivers` had at
   *  least one recognised name — see `topDrivers`. Can legitimately be `[]`
   *  when every stored driver's name was unrecognised; the screen must
   *  still render the headline in that case, just with no driver lines
   *  under it. */
  drivers: readonly ReasoningDriverView[]
}

function deriveLearnedView(learned: PlayerProjectionLearned): ReasoningLearnedView {
  return {
    headline: `Decided by ${learned.modelVersion} · ${learned.expectedPoints.toFixed(1)}`,
    drivers: topDrivers(learned.drivers),
  }
}

// ============================================================================
// Coverage — product-brief.md §8. Every player shown here gets a coverage
// sentence, not just the ones with a gap (design-reference.md/§8: silence on
// a marquee summer signing must not read as a verdict) — this is the one
// place that differs from VerdictCard's coverageNote, which only speaks up
// for the missing-history case.
// ============================================================================

function coverageSentence(name: string, hasHistory: boolean): string {
  return hasHistory
    ? `${name} — built on real Premier League match history.`
    : `${name} — no Premier League history yet; this rests on a position-based estimate, not a season of form.`
}

// ============================================================================
// Captain confidence band — ticket #79's own thresholds, pre-decided in the
// ticket's Notes ("because": product-brief.md §8 says gaps routinely under
// one point are inside the model's own error). Compares the captain's raw
// projected points (never doubled) against the next-highest STARTER in the
// same starting XI — not the next-highest in the full squad.
// ============================================================================

export type CaptainConfidenceBand = ConfidenceBand

/** gap < 0.5 -> coin-flip; 0.5 to 1.5 inclusive -> marginal; > 1.5 -> clear.
 *  Exported so both this file's callers and its own unit tests can name the
 *  thresholds without repeating magic numbers (ticket DoD: boundary values
 *  0.5 and 1.5 exactly are unit-tested). */
export function deriveCaptainConfidenceBand(gap: number): CaptainConfidenceBand {
  const absoluteGap = Math.abs(gap)
  if (absoluteGap > 1.5) return 'clear'
  if (absoluteGap >= 0.5) return 'marginal'
  return 'coin-flip'
}

interface CaptainGap {
  gap: number
  captainId: number
  nextBestId: number
}

/** Finds the captain among the starting XI and the highest-projected
 *  non-captain starter, and returns the (unsigned) gap between them. Null
 *  when there's nothing to compare — no starting XI, no flagged captain, or
 *  a starting XI of exactly one player (defensive; should not happen for a
 *  real eleven). */
function findCaptainGap(startingXI: readonly StartingXIPick[]): CaptainGap | null {
  const captain = startingXI.find((pick) => pick.isCaptain)
  if (!captain) return null

  const others = startingXI.filter((pick) => pick.playerId !== captain.playerId)
  if (others.length === 0) return null

  const nextBest = others.reduce((best, pick) => (pick.expectedPoints > best.expectedPoints ? pick : best), others[0])

  return {
    gap: Math.abs(captain.expectedPoints - nextBest.expectedPoints),
    captainId: captain.playerId,
    nextBestId: nextBest.playerId,
  }
}

function captainNote(band: CaptainConfidenceBand, captainName: string, nextBestName: string): string {
  if (band === 'coin-flip') {
    return `The captaincy is too close to call — ${captainName} and ${nextBestName} cannot be separated on this projection.`
  }
  if (band === 'marginal') {
    return `${captainName} is a marginal pick for captain over ${nextBestName}.`
  }
  return `${captainName} is a clear pick for captain over ${nextBestName}.`
}

// ============================================================================
// Alternatives (Plan B / Plan C) — ticket #102. product-brief.md §6c names
// Plan A / Plan B / Plan C as a core requirement; §8 requires the app to say
// plainly when the top options are statistically indistinguishable. Every
// alternative is rendered as a DIFFERENCE from Plan A, never as a competing
// option in its own right — Plan A never loses its position as the answer
// (this ticket's own Notes). Nothing here re-implements #60's distinctness
// collapse — whatever api.ts hands in is already the distinct set.
// ============================================================================

/** The subset of a plan's fields the difference/description helpers below
 *  need — shared shape for Plan A (via ReasoningRecommendationData) and an
 *  AlternativePlanData, so those two don't have to be structurally
 *  duplicated just to call the same function. */
interface PlanDecisionShape {
  isRoll: boolean
  transferInPlayerId: number | null
  captainPlayerId: number
}

function transferFragment(
  a: PlanDecisionShape,
  b: PlanDecisionShape,
  names: ReadonlyMap<number, string>
): string | null {
  if (a.isRoll && b.isRoll) return null
  if (a.isRoll && !b.isRoll) {
    return `transfers in ${nameFor(b.transferInPlayerId as number, names)} instead of rolling the transfer`
  }
  if (!a.isRoll && b.isRoll) {
    return `rolls the transfer instead of transferring in ${nameFor(a.transferInPlayerId as number, names)}`
  }
  if (a.transferInPlayerId === b.transferInPlayerId) return null
  return `transfers in ${nameFor(b.transferInPlayerId as number, names)} instead of ${nameFor(a.transferInPlayerId as number, names)}`
}

function captainFragment(
  a: PlanDecisionShape,
  b: PlanDecisionShape,
  names: ReadonlyMap<number, string>
): string | null {
  if (a.captainPlayerId === b.captainPlayerId) return null
  return `captains ${nameFor(b.captainPlayerId, names)} instead of ${nameFor(a.captainPlayerId, names)}`
}

/** How an alternative plan differs from Plan A, in one sentence — the
 *  point of showing it at all (this ticket's Notes: "the difference is the
 *  point, not the plan in isolation"). Covers all three tested shapes
 *  (transfer only, captain only, both) plus the defensive case where
 *  neither the transfer nor the captain differs (possible in principle: two
 *  plans that #60 kept distinct on score alone, differing only in the
 *  outgoing player, which isSameDecision deliberately never compares) —
 *  that case still reads as a real sentence, never a blank line. */
export function planDifferenceText(
  planA: PlanDecisionShape,
  alternative: PlanDecisionShape,
  names: ReadonlyMap<number, string>
): string {
  const parts = [transferFragment(planA, alternative, names), captainFragment(planA, alternative, names)].filter(
    (part): part is string => part !== null
  )
  if (parts.length === 0) {
    return 'Differs in projected outcome only — the transfer and captain are the same as Plan A.'
  }
  const sentence = parts.join(' and ')
  return sentence.charAt(0).toUpperCase() + sentence.slice(1) + '.'
}

/** A short, self-contained description of a plan's own decision — "bringing
 *  in {X} and captaining {Y}" / "rolling the transfer and captaining {Y}" —
 *  used only by the coin-flip note below, which has to name BOTH plans in
 *  one sentence rather than phrase one as a diff off the other. */
function planDescription(plan: PlanDecisionShape, names: ReadonlyMap<number, string>): string {
  const transferPart = plan.isRoll
    ? 'rolling the transfer'
    : `bringing in ${nameFor(plan.transferInPlayerId as number, names)}`
  return `${transferPart} and captaining ${nameFor(plan.captainPlayerId, names)}`
}

/** The horizon points gap between an alternative and Plan A — net points
 *  (post-hit), the "real" expected outcome figure, computed purely from the
 *  already-stored net_points_rounded on each plan's own recommendations
 *  row (ticket DoD: "using the figures already stored on recommendations",
 *  no re-derivation). Positive means the alternative projects HIGHER than
 *  Plan A over the horizon. */
export function planPointsGap(planANet: number, alternativeNet: number): number {
  return alternativeNet - planANet
}

function pointsGapLabel(gap: number): string {
  if (gap === 0) return 'Same projected points as Plan A over the horizon.'
  const sign = gap > 0 ? '+' : ''
  return `${sign}${gap} pts vs Plan A over the horizon.`
}

/** Reuses the exact wording convention Plan A's own player rows use
 *  (coverageSentence above) — this ticket's Notes: "extend the same
 *  treatment to the alternatives rather than inventing a new one." */
function alternativePlayerCoverage(
  role: string,
  storageRole: string,
  playerId: number,
  coverage: readonly CoverageEntry[],
  names: ReadonlyMap<number, string>
): ReasoningAlternativePlayerView {
  const name = nameFor(playerId, names)
  const hasHistory = findCoverage(coverage, storageRole, playerId)
  return { role, name, coverageNote: coverageSentence(name, hasHistory) }
}

export interface ReasoningAlternativePlayerView {
  role: string
  name: string
  coverageNote: string
}

export interface ReasoningAlternativeView {
  /** 'Plan B' for plan_index 1, 'Plan C' for plan_index 2. */
  label: string
  differenceText: string
  pointsGap: number
  pointsGapLabel: string
  confidenceWord: ConfidenceBand
  hit: ReasoningHitView | null
  /** This alternative's own first stored reason line, or null when it has
   *  none (ticket DoD: a plan missing its reasons still renders). */
  reasonHeadline: string | null
  players: readonly ReasoningAlternativePlayerView[]
}

const PLAN_LABELS: Readonly<Record<number, string>> = { 1: 'Plan B', 2: 'Plan C' }

function deriveAlternativeView(
  planA: ReasoningRecommendationData,
  alternative: AlternativePlanData
): ReasoningAlternativeView {
  const players: ReasoningAlternativePlayerView[] = []
  if (!alternative.isRoll && alternative.transferInPlayerId !== null) {
    players.push(
      alternativePlayerCoverage(
        'Transfer in',
        'transferIn',
        alternative.transferInPlayerId,
        alternative.coverage,
        planA.playerNames
      )
    )
  }
  if (!alternative.isRoll && alternative.transferOutPlayerId !== null) {
    players.push(
      alternativePlayerCoverage(
        'Transfer out',
        'transferOut',
        alternative.transferOutPlayerId,
        alternative.coverage,
        planA.playerNames
      )
    )
  }
  players.push(
    alternativePlayerCoverage('Captain', 'captain', alternative.captainPlayerId, alternative.coverage, planA.playerNames)
  )

  const gap = planPointsGap(planA.netPointsRounded, alternative.netPointsRounded)

  return {
    label: PLAN_LABELS[alternative.planIndex] ?? `Plan ${alternative.planIndex + 1}`,
    differenceText: planDifferenceText(planA, alternative, planA.playerNames),
    pointsGap: gap,
    pointsGapLabel: pointsGapLabel(gap),
    confidenceWord: alternative.confidenceBand,
    hit:
      alternative.hitCost > 0
        ? { cost: alternative.hitCost, gross: alternative.grossPointsRounded, net: alternative.netPointsRounded }
        : null,
    reasonHeadline: alternative.reasons[0] ?? null,
    players,
  }
}

/** design-reference.md's writing rules: an empty state is an invitation or
 *  a confident answer, never an apology. #60 collapsing plans down to one
 *  IS the confident case ("the week where the recommendation is 'roll your
 *  transfer' is not an empty state") — this note must read the same way. */
const NO_ALTERNATIVE_NOTE = 'This is a confident call — no distinct alternative plan was found for this gameweek.'

/** Plan A's own confidence_band (product-brief.md §8) is derived from the
 *  score gap between Plan A and Plan B specifically (see
 *  src/lib/recommendation/confidence.ts) — so a coin-flip band names Plan A
 *  and its first alternative, never Plan C. Only produced when there IS a
 *  first alternative to name; a coin-flip band with zero stored
 *  alternatives (Plan B collapsed into Plan A as the same decision) falls
 *  through to NO_ALTERNATIVE_NOTE instead, which is the truer story. */
function coinFlipNote(planA: ReasoningRecommendationData, firstAlternative: AlternativePlanData | undefined): string | null {
  if (planA.confidenceBand !== 'coin-flip') return null
  if (!firstAlternative) return null
  return (
    'The top options cannot be separated on this projection: Plan A ' +
    `(${planDescription(planA, planA.playerNames)}) and Plan B ` +
    `(${planDescription(firstAlternative, planA.playerNames)}).`
  )
}

// ============================================================================
// View types
// ============================================================================

export interface ReasoningPlayerView {
  role: string
  name: string
  coverageNote: string
  components: readonly ReasoningComponentRow[]
  /** False when no player_projections row could be resolved for this player
   *  at all — the component list is then empty and the screen must say so,
   *  never render a silently-empty table. */
  hasProjection: boolean
  /** Set only when a `gbm-v1` row resolved for this player (ticket #266) —
   *  null for every player until the nightly job writes `gbm-v1` rows and
   *  the owner switches the active model, at which point the screen adds
   *  the "Decided by gbm-v1" line and top-three drivers above the existing
   *  (now explicitly `baseline-v1`) breakdown. Null leaves the screen
   *  exactly as it rendered before this ticket. */
  learned: ReasoningLearnedView | null
}

export interface ReasoningHitView {
  cost: number
  gross: number
  net: number
}

export type ReasoningViewStatus = 'empty' | 'ready'

export interface ReasoningView {
  status: ReasoningViewStatus
  /** Set only when status is 'empty' — a specific sentence naming what's
   *  missing and what to do (design-reference.md's writing rules), never a
   *  generic error or an indefinite spinner. */
  emptyMessage: string | null
  gameweekName: string | null
  headline: string | null
  reasons: readonly string[]
  horizonLabel: string
  horizonGross: number | null
  horizonNet: number | null
  hit: ReasoningHitView | null
  confidenceWord: ConfidenceBand | null
  players: readonly ReasoningPlayerView[]
  captainBand: CaptainConfidenceBand | null
  captainNote: string | null
  modelVersion: string | null
  computedAtLabel: string | null
  /** Every OTHER stored plan for this gameweek, rendered as a difference off
   *  Plan A — ticket #102. `[]` when Plan A is the only distinct plan #60
   *  left standing; see `alternativesEmptyNote` for that case's wording. */
  alternatives: readonly ReasoningAlternativeView[]
  /** Set only when `alternatives` is empty on an otherwise-ready view — a
   *  confident sentence, never an apology (design-reference.md's writing
   *  rules; see NO_ALTERNATIVE_NOTE). Null whenever alternatives.length > 0
   *  and null on the top-level 'empty' status (that case has its own
   *  emptyMessage already). */
  alternativesEmptyNote: string | null
  /** Set only when Plan A's own confidence_band is 'coin-flip' AND there is
   *  a first alternative to name (product-brief.md §8) — states plainly
   *  that the top two options cannot be separated, naming both. Null
   *  otherwise. */
  coinFlipNote: string | null
}

const EMPTY_MESSAGE =
  'No recommendation to explain yet — run scripts/generate-recommendations.ts to produce this ' +
  "gameweek's plan, then reload this page."

/** Fixed role display order — transfer-in, transfer-out, captain,
 *  vice-captain — matching the order the ticket's own scope list names
 *  them in. A roll plan has no transfer-in/out, so those two are simply
 *  skipped rather than shown as a gap. */
const ROLE_ORDER: ReadonlyArray<{
  role: 'transferIn' | 'transferOut' | 'captain' | 'viceCaptain'
  label: string
  idOf: (data: ReasoningRecommendationData) => number | null
}> = [
  { role: 'transferIn', label: 'Transfer in', idOf: (d) => d.transferInPlayerId },
  { role: 'transferOut', label: 'Transfer out', idOf: (d) => d.transferOutPlayerId },
  { role: 'captain', label: 'Captain', idOf: (d) => d.captainPlayerId },
  { role: 'viceCaptain', label: 'Vice-captain', idOf: (d) => d.viceCaptainPlayerId },
]

function findCoverage(
  coverage: ReasoningRecommendationData['coverage'],
  role: string,
  playerId: number
): boolean {
  // Default true (no coverage gap) when nothing was stored for this
  // role/player — coverage rows only exist for players actually checked at
  // generation time (recommendation_reasons/coverage precedent, see
  // src/lib/recommendation/coverage.ts). A missing entry is not evidence of
  // a gap; only an explicit `hasHistory: false` row is.
  const entry = coverage.find((c) => c.role === role && c.playerId === playerId)
  return entry?.hasHistory ?? true
}

function projectionFor(
  projections: ReadonlyMap<number, PlayerProjectionData>,
  playerId: number
): PlayerProjectionData | null {
  return projections.get(playerId) ?? null
}

export function deriveReasoningView(data: ReasoningRecommendationData | null): ReasoningView {
  if (!data) {
    return {
      status: 'empty',
      emptyMessage: EMPTY_MESSAGE,
      gameweekName: null,
      headline: null,
      reasons: [],
      horizonLabel: 'Horizon unavailable',
      horizonGross: null,
      horizonNet: null,
      hit: null,
      confidenceWord: null,
      players: [],
      captainBand: null,
      captainNote: null,
      modelVersion: null,
      computedAtLabel: null,
      alternatives: [],
      alternativesEmptyNote: null,
      coinFlipNote: null,
    }
  }

  const headline =
    data.reasons[0] ?? (data.isRoll ? 'Roll your transfer.' : 'A transfer is recommended.')

  const players: ReasoningPlayerView[] = ROLE_ORDER.filter((entry) => entry.idOf(data) !== null).map(
    (entry) => {
      const playerId = entry.idOf(data) as number
      const name = nameFor(playerId, data.playerNames)
      const hasHistory = findCoverage(data.coverage, entry.role, playerId)
      const projection = projectionFor(data.projections, playerId)
      return {
        role: entry.label,
        name,
        coverageNote: coverageSentence(name, hasHistory),
        components: projection ? pointsToRows(projection.points) : [],
        hasProjection: projection !== null,
        learned: projection?.learned ? deriveLearnedView(projection.learned) : null,
      }
    }
  )

  const hit =
    data.hitCost > 0
      ? { cost: data.hitCost, gross: data.grossPointsRounded, net: data.netPointsRounded }
      : null

  const horizonLabel =
    data.horizon !== null
      ? `Projected across ${data.horizon} gameweek${data.horizon === 1 ? '' : 's'}`
      : 'Horizon unavailable'

  // Model version / computed-at: taken from whichever named player's
  // projection resolved first, in ROLE_ORDER — every row written for one
  // gameweek by one job run shares the same model_version and computed_at
  // (scripts/project-points.ts writes both from one MODEL_VERSION constant
  // and one `new Date()` per run), so any resolved player's row is
  // representative. Null when no projection resolved for anyone.
  const firstProjection = ROLE_ORDER.map((entry) => entry.idOf(data))
    .filter((id): id is number => id !== null)
    .map((id) => projectionFor(data.projections, id))
    .find((p): p is PlayerProjectionData => p !== null)

  const modelVersion = firstProjection?.modelVersion ?? null
  const computedAtLabel = firstProjection ? formatSyncTimestamp(firstProjection.computedAt) : null

  let captainBand: CaptainConfidenceBand | null = null
  let captainNoteText: string | null = null
  if (data.startingXI) {
    const found = findCaptainGap(data.startingXI)
    if (found) {
      captainBand = deriveCaptainConfidenceBand(found.gap)
      const captainName = nameFor(found.captainId, data.playerNames)
      const nextBestName = nameFor(found.nextBestId, data.playerNames)
      captainNoteText = captainNote(captainBand, captainName, nextBestName)
    }
  }

  const alternatives = data.alternatives.map((alternative) => deriveAlternativeView(data, alternative))

  return {
    status: 'ready',
    emptyMessage: null,
    gameweekName: data.gameweekName,
    headline,
    reasons: data.reasons,
    horizonLabel,
    // The horizon TOTAL (recommendations.gross_points_rounded/
    // net_points_rounded) is a separate stored figure from the horizon
    // COUNT (solver_runs.horizon) used only for horizonLabel above — one
    // being unresolvable must not blank the other. A missing horizon count
    // means the label reads "Horizon unavailable" while the total itself
    // still renders; see derive.test.ts.
    horizonGross: data.grossPointsRounded,
    horizonNet: data.netPointsRounded,
    hit,
    confidenceWord: data.confidenceBand,
    players,
    captainBand,
    captainNote: captainNoteText,
    modelVersion,
    computedAtLabel,
    alternatives,
    alternativesEmptyNote: alternatives.length === 0 ? NO_ALTERNATIVE_NOTE : null,
    coinFlipNote: coinFlipNote(data, data.alternatives[0]),
  }
}

